FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get install -y software-properties-common

RUN apt-get update

RUN apt-get install git -y

RUN apt-get update

RUN apt-get install -y zip

RUN apt-get install -y unzip
